# Generated by Django 5.2 on 2025-05-03 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name="Nom de l'équipement")),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='Salle.salle', verbose_name='Salle associée')),
            ],
        ),
    ]
