# Generated by Django 4.2 on 2025-05-17 19:12

import Salle.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name="Nom de l'équipement")),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('couleur', models.CharField(max_length=150, verbose_name="Couleur de l'equipement")),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('Stock_Total', models.PositiveIntegerField(verbose_name='Stock total')),
                ('image', models.ImageField(upload_to=Salle.models.equipement_image_path, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nom de la salle')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=Salle.models.salle_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Equipements_Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantite dans la salle')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='Salle.equipement')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_salle', to='Salle.salle')),
            ],
        ),
    ]
