# Generated by Django 4.2 on 2025-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='etat',
            field=models.CharField(choices=[('attente', 'En attente'), ('accepte', 'Acceptée'), ('refuse', 'Refusée'), ('annule', 'Annulée')], default='attente', max_length=10, verbose_name='État'),
        ),
    ]
